name: 'The Elisabeth Irwin Center for Experience & Inquiry'
favicon: null
layout_spectrum: 0.40256518102250993
typography_spectrum: 0.0006905903574079275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6593303186818957
  lightness: 0.7000340449158102
  saturation: 0.7857105538714677
  rhythmicContrast: 0.3930034770164639
purpose: []
