name: 'The Elisabeth Irwin Center for Experience & Inquiry'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86957
title: 'A Community of Creativity, Collaboration & Consequence'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed171f'
    - '#ffffff'
    - '#f25157'
    - '#f68c90'
    - '#fac6c8'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
